export const tb_planosacademia = [
  {
    id: 1,
    qtd_mes_plano: 1,
    tipo_plano: "MENSAL",
    valor_plano: 120,
    academia_id: 2,
  },
  {
    id: 2,
    qtd_mes_plano: 2,
    tipo_plano: "BIMESTRAL",
    valor_plano: 120,
    academia_id: 2,
  },
  {
    id: 3,
    qtd_mes_plano: 1,
    tipo_plano: "MENSAL",
    valor_plano: 65,
    academia_id: 3,
  },
  {
    id: 4,
    qtd_mes_plano: 1,
    tipo_plano: "MENSAL",
    valor_plano: 60,
    academia_id: 1,
  },
  {
    id: 5,
    qtd_mes_plano: 2,
    tipo_plano: "BIMESTRAL",
    valor_plano: 120,
    academia_id: 3,
  },
  {
    id: 6,
    qtd_mes_plano: 3,
    tipo_plano: "TRIMESTRAL",
    valor_plano: 175,
    academia_id: 3,
  },
  {
    id: 7,
    qtd_mes_plano: 6,
    tipo_plano: "SEMESTRAL",
    valor_plano: 0,
    academia_id: 3,
  },
  {
    id: 8,
    qtd_mes_plano: 12,
    tipo_plano: "ANUAL",
    valor_plano: 650,
    academia_id: 3,
  },
  {
    id: 9,
    qtd_mes_plano: 2,
    tipo_plano: "BIMESTRAL",
    valor_plano: 200,
    academia_id: 1,
  },
  {
    id: 10,
    qtd_mes_plano: 3,
    tipo_plano: "TRIMESTRAL",
    valor_plano: 250,
    academia_id: 1,
  },
  {
    id: 11,
    qtd_mes_plano: 3,
    tipo_plano: "TRIMESTRAL",
    valor_plano: 250,
    academia_id: 2,
  },
  {
    id: 12,
    qtd_mes_plano: 1,
    tipo_plano: "MENSAL",
    valor_plano: 140,
    academia_id: 6,
  },
  {
    id: 13,
    qtd_mes_plano: 1,
    tipo_plano: "MENSAL",
    valor_plano: 60,
    academia_id: 8,
  },
  {
    id: 14,
    qtd_mes_plano: 1,
    tipo_plano: "MENSAL",
    valor_plano: 60,
    academia_id: 9,
  },
  {
    id: 15,
    qtd_mes_plano: 1,
    tipo_plano: "MENSAL",
    valor_plano: 70,
    academia_id: 10,
  },
  {
    id: 16,
    qtd_mes_plano: 1,
    tipo_plano: "MENSAL",
    valor_plano: 65,
    academia_id: 12,
  },
];
