export const tb_planos_personalizado = [
  {
    id: 1,
    nome_plano_personalizado: "Familia/ Casal",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 60,
    academia_id: 3,
  },
  {
    id: 2,
    nome_plano_personalizado: "Box",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 55,
    academia_id: 3,
  },
  {
    id: 3,
    nome_plano_personalizado: "3 dias na Semana",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 50,
    academia_id: 3,
  },
  {
    id: 4,
    nome_plano_personalizado: "Plano Teste",
    qtd_dias_plano: 15,
    valor_plano_personalizado: 100,
    academia_id: 1,
  },
  {
    id: 5,
    nome_plano_personalizado: "Corre",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 50,
    academia_id: 3,
  },
  {
    id: 6,
    nome_plano_personalizado: "Coletivo 2 vezes",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 90,
    academia_id: 6,
  },
  {
    id: 7,
    nome_plano_personalizado: "Coletivo 1 vezes",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 75,
    academia_id: 6,
  },
  {
    id: 8,
    nome_plano_personalizado: "Coletivo 3 vezes",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 105,
    academia_id: 6,
  },
  {
    id: 9,
    nome_plano_personalizado: "Coletivo 4 vezes",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 120,
    academia_id: 6,
  },
  {
    id: 10,
    nome_plano_personalizado: "JIU JISTU",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 100,
    academia_id: 1,
  },
  {
    id: 11,
    nome_plano_personalizado: "Plano Família ",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 55,
    academia_id: 2,
  },
  {
    id: 12,
    nome_plano_personalizado: "Teste",
    qtd_dias_plano: 45,
    valor_plano_personalizado: 200,
    academia_id: 2,
  },
  {
    id: 13,
    nome_plano_personalizado: "Plano Acad/Danca",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 75,
    academia_id: 3,
  },
  {
    id: 14,
    nome_plano_personalizado: "Plano Familia",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 50,
    academia_id: 8,
  },
  {
    id: 15,
    nome_plano_personalizado: "JIU JISTU",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 60,
    academia_id: 9,
  },
  {
    id: 16,
    nome_plano_personalizado: "A",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 1,
    academia_id: 9,
  },
  {
    id: 17,
    nome_plano_personalizado: "B",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 2,
    academia_id: 9,
  },
  {
    id: 18,
    nome_plano_personalizado: "Treino e esteira",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 100,
    academia_id: 12,
  },
  {
    id: 19,
    nome_plano_personalizado: "jessica nayra",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 60,
    academia_id: 12,
  },
  {
    id: 20,
    nome_plano_personalizado: "Três dias ",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 55,
    academia_id: 12,
  },
  {
    id: 21,
    nome_plano_personalizado: "mensal 2",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 60,
    academia_id: 12,
  },
  {
    id: 22,
    nome_plano_personalizado: "mensal 3",
    qtd_dias_plano: 30,
    valor_plano_personalizado: 55,
    academia_id: 12,
  },
];
