export const tb_usuario = [
  {
    id: 1,
    email: "elysonvinicius@outlook.com",
    expiracao_user: "NULL",
    login: "Elyson2k",
    nome: "Elyson Vinicius Silva Melo",
    nome_academia: "NULL",
    numero_telefone: "(00) 0 0000-0000",
    password: "$2a$10$3K2j5mYiSs12sTzfc8AmkuDaSx3/noOXL3yPXRlz0X1JVVGDykF7S",
    preference_id: "298657653-c2a3e986-b99c-4929-a1db-94b4485e3cab",
    role: "ADMIN",
    token_recuperar: "NULL",
    user_verificado: "_binary '\u0000",
    verificacao_wpp: "_binary '\u0000",
    academia_id: 1,
    plano_user_id: "NULL",
  },
  {
    id: 2,
    email: "derickjesiel96@gmail.com",
    expiracao_user: "NULL",
    login: "DerickC",
    nome: "Derick Carvalho",
    nome_academia: "NULL",
    numero_telefone: "(84) 9 9999-9999",
    password: "$2a$10$TY.105wsu1DYLMTNPKSg3Obgpdpj/vK6Bl/Ce38DguN7BV55MRPya",
    preference_id: "298657653-2d7529e3-917c-4590-aed2-4d695d928107",
    role: "ADMIN",
    token_recuperar: "NULL",
    user_verificado: "_binary '\u0001",
    verificacao_wpp: "_binary '\u0000",
    academia_id: 2,
    plano_user_id: 2,
  },
  {
    id: 3,
    email: "js506376@gmail.com",
    expiracao_user: "NULL",
    login: "Maria123",
    nome: "Jefferson Jairo Martins",
    nome_academia: "NULL",
    numero_telefone: "(84) 9 9420-1260",
    password: "$2a$10$DQVxSsw8ro5KextM.snkwOiPW8ZX33lEc76gb5pDQZLMkdWAw9Cn6",
    preference_id: "298657653-abfafc19-4b8c-4e6b-91ef-5971bfa2bac5",
    role: "ADMIN",
    token_recuperar: "NULL",
    user_verificado: "_binary '\u0001",
    verificacao_wpp: "_binary '\u0000",
    academia_id: 3,
    plano_user_id: 3,
  },
  {
    id: 4,
    email: "walquiria.lopes11@gmail.com",
    expiracao_user: "NULL",
    login: "walquirial",
    nome: "Walquiria Lopes",
    nome_academia: "NULL",
    numero_telefone: "(67) 9 8214-2438",
    password: "$2a$10$AN9Tucp5CdUTHwgOAXOeP.IsYvim/4tYT0mjmWIIl4hImlNLJQgbi",
    preference_id: "NULL",
    role: "ADMIN",
    token_recuperar: "NULL",
    user_verificado: "_binary '\u0000",
    verificacao_wpp: "_binary '\u0000",
    academia_id: 4,
    plano_user_id: "NULL",
  },
  {
    id: 5,
    email: "brunalouisecarvalho@gmail.com",
    expiracao_user: "NULL",
    login: "brcarvalho",
    nome: "Bruna Louise Rafaela Carvalho",
    nome_academia: "NULL",
    numero_telefone: "(19) 9 9370-0953",
    password: "$2a$10$nVqq8jepuBmc7WAt.iWEMeDvggyZtZ1OpIUgmrMUPlDXRCnjKYJG.",
    preference_id: "NULL",
    role: "ADMIN",
    token_recuperar: "NULL",
    user_verificado: "_binary '\u0000",
    verificacao_wpp: "_binary '\u0000",
    academia_id: 5,
    plano_user_id: "NULL",
  },
  {
    id: 6,
    email: "mateusbertolbbb@gmail.com",
    expiracao_user: "NULL",
    login: "bertol",
    nome: "Mateus Bertol ",
    nome_academia: "NULL",
    numero_telefone: "(51) 9 8159-6728",
    password: "$2a$10$b9YxZBZ..of72txO.DlXnOPFuSAyRaFCk/11jPYohljnTUSmIGRJy",
    preference_id: "298657653-4fb8f533-bffa-4eca-9302-54b1409bd3e3",
    role: "ADMIN",
    token_recuperar: "NULL",
    user_verificado: "_binary '\u0000",
    verificacao_wpp: "_binary '\u0000",
    academia_id: 6,
    plano_user_id: "NULL",
  },
  {
    id: 7,
    email: "testeusuario@mailinator.com",
    expiracao_user: "NULL",
    login: "teste123",
    nome: "Usuario Teste",
    nome_academia: "NULL",
    numero_telefone: "(99) 9 9999-9999",
    password: "$2a$10$vpIeReXPTXTWCV7prlVqNOAlz8lI5KyV.H6/HcCk9Ck91Bb8wB65a",
    preference_id: "NULL",
    role: "ADMIN",
    token_recuperar: "NULL",
    user_verificado: "_binary '\u0000",
    verificacao_wpp: "_binary '\u0000",
    academia_id: 7,
    plano_user_id: "NULL",
  },
  {
    id: 8,
    email: "teste@gmail.com",
    expiracao_user: "NULL",
    login: "testeAcad",
    nome: "Usuário Teste",
    nome_academia: "NULL",
    numero_telefone: "(99) 9 9999-9999",
    password: "$2a$10$/2074qTnEB1/vYc7UaCHseVi3.3k6D5Dljmq0ZTD/jQCNZydt.tY.",
    preference_id: "NULL",
    role: "ADMIN",
    token_recuperar: "NULL",
    user_verificado: "_binary '\u0000",
    verificacao_wpp: "_binary '\u0000",
    academia_id: 8,
    plano_user_id: "NULL",
  },
  {
    id: 9,
    email: "elysonvinicius333@outlook.com",
    expiracao_user: "NULL",
    login: "Elyson2k2",
    nome: "Elyson Vinicius Silva Melo",
    nome_academia: "NULL",
    numero_telefone: "(84) 9 9953-8631",
    password: "$2a$10$Lqms8Sa87BZSETm5fGTrYe.rYnUZlfFJQs3S/dZ7gsvg0XToBUDFu",
    preference_id: "NULL",
    role: "ADMIN",
    token_recuperar: "NULL",
    user_verificado: "_binary '\u0000",
    verificacao_wpp: "_binary '\u0000",
    academia_id: 9,
    plano_user_id: "NULL",
  },
  {
    id: 10,
    email: "elysonviniciusss@outlook.com",
    expiracao_user: "NULL",
    login: "Elison2kk",
    nome: "Elyson Vinicius Silva Melo",
    nome_academia: "NULL",
    numero_telefone: "(84) 9 9953-8631",
    password: "$2a$10$q411WgVoP6ttAfYnrJCEvuimtuMin7v/V9zOdbE9/ngeesQ95ViQK",
    preference_id: "298657653-1e37438e-ec4a-41d2-8d66-13d522a451ce",
    role: "ADMIN",
    token_recuperar: "NULL",
    user_verificado: "_binary '\u0000",
    verificacao_wpp: "_binary '\u0000",
    academia_id: 10,
    plano_user_id: "NULL",
  },
  {
    id: 11,
    email: "lucaassump@gmail.com",
    expiracao_user: "NULL",
    login: "lucad",
    nome: "Luca",
    nome_academia: "NULL",
    numero_telefone: "(11) 1 1111-1111",
    password: "$2a$10$pF8bB2hh8U4ejraCoftNTuC3dPF7Qns/AOYa/OK68mqxZlpl7KVCK",
    preference_id: "NULL",
    role: "ADMIN",
    token_recuperar: "NULL",
    user_verificado: "_binary '\u0000",
    verificacao_wpp: "_binary '\u0000",
    academia_id: 11,
    plano_user_id: "NULL",
  },
  {
    id: 12,
    email: "forcavital52@gmail.com",
    expiracao_user: "2025-05-02",
    login: "forcavital",
    nome: "telany freitas",
    nome_academia: "NULL",
    numero_telefone: "(84) 9 9444-0557",
    password: "$2a$10$P7kxaY36X7EmHuEYjLbmouTqycBE2MEZys4v54U.UsdUbxRcwlIHm",
    preference_id: "298657653-751452d4-43bb-4360-8c2f-cf997f498bc7",
    role: "ADMIN",
    token_recuperar: "NULL",
    user_verificado: "_binary '\u0001",
    verificacao_wpp: "_binary '\u0000",
    academia_id: 12,
    plano_user_id: 1,
  },
];
